import mongoose from 'mongoose';;

const coolerSchema= new mongoose.Schema(
    {
        companyName:
        {
            type:String,
            required:true,
        },
        seller_ref:
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:'User'
        },
        comboId:
        {
            type:String,
            required:true,
        },
        imgUrl:
        [
            {
                type:String,
                required:true,
            },
        ],
        price:
        {
            type:Number,
            required:true,
        },
        modelName:
        {
            type:String,
            required:true,
        },
        color:
        {
            type:String,
            required:true,
        },
        coolerType:
        {
            type:String,
            required:true,
        },
        bodyMaterial:
        {
            type:String,
            required:true,
        },
        numberofSpeeds:
        {
            type:Number,
            required:true,
        },  
        blowerOrFan:
        {
            type:String,
            required:true,
        },
        coolingMedia:
        {
             type:String,
        },
        remoteSupport:
        {
            type:String,
            required:true,
        },
        operatingMode:
        {
            type:String,
        },
        capacity:
        {
            type:String,
            required:true,
        },
        warranty:
        {
            type:String,
            required:true,
        },
        quantity:
        {
            type:Number,
            required:true,
        } 
    },
    {
        timestamp: true,
    })

    const Cooler= mongoose.model('Cooler', coolerSchema);
    export default Cooler;